#############################################################################
# Makefile for building: Build
# Generated by qmake (2.01a) (Qt 4.7.0) on: ?? 11. ??? 15:49:43 2011
# Project:  Build.pro
# Template: subdirs
# Command: c:\qt\2010.05\qt\bin\qmake.exe -spec c:\Qt\2010.05\qt\mkspecs\win32-g++ CONFIG+=release -o Makefile Build.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = c:\qt\2010.05\qt\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-src \
		sub-ambilight

src\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src\ $(MKDIR) src\ 
	cd src\ && $(QMAKE) d:\Install\Programing\QT\Ambilight\src\src.pro -spec c:\Qt\2010.05\qt\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src\ $(MKDIR) src\ 
	cd src\ && $(QMAKE) d:\Install\Programing\QT\Ambilight\src\src.pro -spec c:\Qt\2010.05\qt\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-src: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default-ordered: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_default: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first-ordered: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) first
sub-src-make_first: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) first
sub-src-all-ordered: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) all
sub-src-all: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean-ordered: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) clean
sub-src-clean: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean-ordered: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-distclean: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets-ordered: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) install
sub-src-install_subtargets: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets-ordered: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-src-uninstall_subtargets: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) uninstall
ambilight\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) ambilight\ $(MKDIR) ambilight\ 
	cd ambilight\ && $(QMAKE) d:\Install\Programing\QT\Ambilight\ambilight\ambilight.pro -spec c:\Qt\2010.05\qt\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-ambilight-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) ambilight\ $(MKDIR) ambilight\ 
	cd ambilight\ && $(QMAKE) d:\Install\Programing\QT\Ambilight\ambilight\ambilight.pro -spec c:\Qt\2010.05\qt\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-ambilight: ambilight\$(MAKEFILE) FORCE
	cd ambilight\ && $(MAKE) -f $(MAKEFILE)
sub-ambilight-make_default-ordered: ambilight\$(MAKEFILE) sub-src-make_default-ordered  FORCE
	cd ambilight\ && $(MAKE) -f $(MAKEFILE) 
sub-ambilight-make_default: ambilight\$(MAKEFILE) FORCE
	cd ambilight\ && $(MAKE) -f $(MAKEFILE) 
sub-ambilight-make_first-ordered: ambilight\$(MAKEFILE) sub-src-make_first-ordered  FORCE
	cd ambilight\ && $(MAKE) -f $(MAKEFILE) first
sub-ambilight-make_first: ambilight\$(MAKEFILE) FORCE
	cd ambilight\ && $(MAKE) -f $(MAKEFILE) first
sub-ambilight-all-ordered: ambilight\$(MAKEFILE) sub-src-all-ordered  FORCE
	cd ambilight\ && $(MAKE) -f $(MAKEFILE) all
sub-ambilight-all: ambilight\$(MAKEFILE) FORCE
	cd ambilight\ && $(MAKE) -f $(MAKEFILE) all
sub-ambilight-clean-ordered: ambilight\$(MAKEFILE) sub-src-clean-ordered  FORCE
	cd ambilight\ && $(MAKE) -f $(MAKEFILE) clean
sub-ambilight-clean: ambilight\$(MAKEFILE) FORCE
	cd ambilight\ && $(MAKE) -f $(MAKEFILE) clean
sub-ambilight-distclean-ordered: ambilight\$(MAKEFILE) sub-src-distclean-ordered  FORCE
	cd ambilight\ && $(MAKE) -f $(MAKEFILE) distclean
sub-ambilight-distclean: ambilight\$(MAKEFILE) FORCE
	cd ambilight\ && $(MAKE) -f $(MAKEFILE) distclean
sub-ambilight-install_subtargets-ordered: ambilight\$(MAKEFILE) sub-src-install_subtargets-ordered  FORCE
	cd ambilight\ && $(MAKE) -f $(MAKEFILE) install
sub-ambilight-install_subtargets: ambilight\$(MAKEFILE) FORCE
	cd ambilight\ && $(MAKE) -f $(MAKEFILE) install
sub-ambilight-uninstall_subtargets-ordered: ambilight\$(MAKEFILE) sub-src-uninstall_subtargets-ordered  FORCE
	cd ambilight\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-ambilight-uninstall_subtargets: ambilight\$(MAKEFILE) FORCE
	cd ambilight\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: Build.pro  c:/Qt/2010.05/qt/mkspecs/win32-g++/qmake.conf c:/Qt/2010.05/qt/mkspecs/qconfig.pri \
		c:/Qt/2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		c:/Qt/2010.05/qt/mkspecs/features/qt_functions.prf \
		c:/Qt/2010.05/qt/mkspecs/features/qt_config.prf \
		c:/Qt/2010.05/qt/mkspecs/features/exclusive_builds.prf \
		c:/Qt/2010.05/qt/mkspecs/features/default_pre.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/default_pre.prf \
		c:/Qt/2010.05/qt/mkspecs/features/release.prf \
		c:/Qt/2010.05/qt/mkspecs/features/debug_and_release.prf \
		c:/Qt/2010.05/qt/mkspecs/features/default_post.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/default_post.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/rtti.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/exceptions.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/stl.prf \
		c:/Qt/2010.05/qt/mkspecs/features/shared.prf \
		c:/Qt/2010.05/qt/mkspecs/features/warn_on.prf \
		c:/Qt/2010.05/qt/mkspecs/features/qt.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/thread.prf \
		c:/Qt/2010.05/qt/mkspecs/features/moc.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/windows.prf \
		c:/Qt/2010.05/qt/mkspecs/features/resources.prf \
		c:/Qt/2010.05/qt/mkspecs/features/uic.prf \
		c:/Qt/2010.05/qt/mkspecs/features/yacc.prf \
		c:/Qt/2010.05/qt/mkspecs/features/lex.prf \
		c:/Qt/2010.05/qt/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec c:\Qt\2010.05\qt\mkspecs\win32-g++ CONFIG+=release -o Makefile Build.pro
c:\Qt\2010.05\qt\mkspecs\qconfig.pri:
c:\Qt\2010.05\qt\mkspecs\modules\qt_webkit_version.pri:
c:\Qt\2010.05\qt\mkspecs\features\qt_functions.prf:
c:\Qt\2010.05\qt\mkspecs\features\qt_config.prf:
c:\Qt\2010.05\qt\mkspecs\features\exclusive_builds.prf:
c:\Qt\2010.05\qt\mkspecs\features\default_pre.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\default_pre.prf:
c:\Qt\2010.05\qt\mkspecs\features\release.prf:
c:\Qt\2010.05\qt\mkspecs\features\debug_and_release.prf:
c:\Qt\2010.05\qt\mkspecs\features\default_post.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\default_post.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\rtti.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\exceptions.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\stl.prf:
c:\Qt\2010.05\qt\mkspecs\features\shared.prf:
c:\Qt\2010.05\qt\mkspecs\features\warn_on.prf:
c:\Qt\2010.05\qt\mkspecs\features\qt.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\thread.prf:
c:\Qt\2010.05\qt\mkspecs\features\moc.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\windows.prf:
c:\Qt\2010.05\qt\mkspecs\features\resources.prf:
c:\Qt\2010.05\qt\mkspecs\features\uic.prf:
c:\Qt\2010.05\qt\mkspecs\features\yacc.prf:
c:\Qt\2010.05\qt\mkspecs\features\lex.prf:
c:\Qt\2010.05\qt\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec c:\Qt\2010.05\qt\mkspecs\win32-g++ CONFIG+=release -o Makefile Build.pro

qmake_all: sub-src-qmake_all sub-ambilight-qmake_all FORCE

make_default: sub-src-make_default-ordered sub-ambilight-make_default-ordered FORCE
make_first: sub-src-make_first-ordered sub-ambilight-make_first-ordered FORCE
all: sub-src-all-ordered sub-ambilight-all-ordered FORCE
clean: sub-src-clean-ordered sub-ambilight-clean-ordered FORCE
distclean: sub-src-distclean-ordered sub-ambilight-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets-ordered sub-ambilight-install_subtargets-ordered FORCE
uninstall_subtargets: sub-src-uninstall_subtargets-ordered sub-ambilight-uninstall_subtargets-ordered FORCE

sub-src-sub_Debug_ordered: src\$(MAKEFILE)
	cd src\ && $(MAKE) debug
sub-ambilight-sub_Debug_ordered: ambilight\$(MAKEFILE) sub-src-sub_Debug_ordered 
	cd ambilight\ && $(MAKE) debug
debug: sub-src-sub_Debug_ordered sub-ambilight-sub_Debug_ordered

sub-src-sub_Release_ordered: src\$(MAKEFILE)
	cd src\ && $(MAKE) release
sub-ambilight-sub_Release_ordered: ambilight\$(MAKEFILE) sub-src-sub_Release_ordered 
	cd ambilight\ && $(MAKE) release
release: sub-src-sub_Release_ordered sub-ambilight-sub_Release_ordered

sub-src-check_ordered: src\$(MAKEFILE)
	cd src\ && $(MAKE) check
sub-ambilight-check_ordered: ambilight\$(MAKEFILE) sub-src-check_ordered 
	cd ambilight\ && $(MAKE) check
check: sub-src-check_ordered sub-ambilight-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

